export const AUTH_LOGIN = 'LOGIN'
export const AUTH_LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const AUTH_LOGIN_FAIL = 'LOGIN_FAIL'

export const AUTH_REGISTER = 'REGISTER'
export const AUTH_REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const AUTH_REGISTER_FAIL = 'REGISTER_FAIL'

export const SET_MESSAGE = 'SET_MESSAGE'
